name: pkg.pr.new

on:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
  # pull_request:
  # push:
  #   branches:
  #     - '**'
  #   tags:
  #     - '!**'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - run: corepack enable

      - uses: actions/setup-node@v4
        with:
          node-version: lts/*
          cache: pnpm

      - name: Install Dependencies
        run: pnpm i --frozen-lockfile

      - name: Build
        run: pnpm build

      - name: Release to pkg.pr.new
        run: pnpm dlx pkg-pr-new publish --pnpm
